roles:
  # pvwa git repo
- src: https://github.com/cyberark/pvwa.git
  type : git
  version: v12.1
# cpm git repo
- src: https://github.com/cyberark/cpm.git
  type : git
  version: v12.1
# psm git repo
- src: https://github.com/cyberark/psm.git
  type : git
  version: v12.0
