roles:
  # pvwa git repo
- src: https://github.com/bab29/pvwa.git
  type : git
# cpm git repo
- src: https://github.com/bab29/cpm.git
  type : git
# psm git repo
- src: https://github.com/bab29/psm.git
  type : git
collections:
- name: community.windows
