# pvwa git repo
- src: https://github.com/bab29/pvwa.git
  scm: git

# cpm git repo
- src: https://github.com/bab29/cpm.git
  scm: git

# psm git repo
- src: https://github.com/bab29/psm.git
  scm: git
